#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Console\Application;

$app = new Application();

$app
    ->chdir(__DIR__)
    ->addCommandsPath('src/Transmission/Command', 'Transmission\\Command')
    ->loadCommands()
    ->run();
